

server
{
    listen 80;
    server_name localhost  rlamlaik.42.fr;
    root /var/www/html;



    #enable https
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php;

    location /
    {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$
    {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        set $wordpress_upstream wordpress;
        fastcgi_pass $wordpress_upstream:9000;
        fastcgi_index index.php;
    }

}


