# here is the compose file work flow in every layer



#first we define the services we want to run in our application,
# in this case we have a web service and a database service

services: # this is where we define the services that we want to run in our application
  nginx: #on every service we can define ports, volumes, environment variables, and other settings
    build: ./requirements/nginx # this specifies the path to the Dockerfile that we want to use to build the image for this service
    ports:
      - "443:443" # this maps port 8443 on the host to port 443 on the container
    depends_on:
      - wordpress # this specifies that the nginx service depends on the wordpress service, so it will wait for the wordpress service to be up and running before starting
    volumes:
      - wp_data:/var/www/html # this mounts the wp_data volume to /var/www/html in the container, so any changes made to the files in /var/www/html will be persisted in the wp_data volume
    networks:
      - inception_net # this specifies that the nginx service is connected to the inception_net network
    container_name: nginx
  mariadb:
    build: ./requirements/mariadb
    image: inception-mariadb:latest
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception_net
    container_name: mariadb
  wordpress:
    build: ./requirements/wordpress # this specifies the path to the Dockerfile that we want to use to build the image for this service, if we didnt specify this it would use the image specified in the image field
    image: inception-wordpress:latest
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
      - wp_password
      - wp_admin_password
    networks:
      - inception_net
    container_name: wordpress



volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/osboxes/data/wp_data

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/osboxes/data/mariadb_data
#the type of those volumes is named volume, which means that they are managed by Docker and can be shared between containers.
# volumes:
#   wp_data: # this is the name of the volume that we want to use for the wordpress service
#     driver: local # this specifies that we want to use the local driver for our volumes, which means that the volumes will be stored on the local filesystem of the host machine
#     driver_opts: # this is where we can specify options for the driver that we are using for our volumes
#     type: none # this specifies that we want to use the none type for our volumes, which means that the volumes will not be managed by Docker and will not be shared between containers
#     o: bind # this specifies that we want to use the bind option for our volumes, which means that the volumes will be mounted as a bind mount, which allows us to share files between the host machine and the containers
#     device: /home/rlamlaik/data/wp_data/ # this specifies the path to the directory on the host machine that we want to use for our volumes
#   # this is the name of the volume that we want to use for the wordpress service
#   mariadb_data: # this is the name of the volume that we want to use for the mariadb service
#     driver: local # this specifies that we want to use the local driver for our volumes, which means that the volumes will be stored on the local filesystem of the host machine
#     driver_opts: # this is where we can specify options for the driver that we are using for our volumes
#     type: none # this specifies that we want to use the none type for our volumes,
#     device: /home/rlamlaik/data/mariadb_data/ # this specifies the path to the directory on the host machine that we want to use for our volumes
#     o: bind # this specifies that we want to use the bind option for our volumes, which means that the volumes will be mounted as a bind mount, which allows us to share files between the host machine and the containers
secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_password:
    file: ../secrets/db_password
  wp_password:
    file: ../secrets/wp_password
  wp_admin_password:
    file: ../secrets/wp_admin_password

networks:
  inception_net: #brige allready by default but we can specify it to be more clea4r
    driver: bridge


# add the nmae t