server {
    listen 443 ssl;

    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php;

    server_name 127.0.0.1;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_param HTTPS 1;
        fastcgi_param HTTP_HOST 127.0.0.1:8443;
        fastcgi_param SERVER_NAME 127.0.0.1;
        fastcgi_param SERVER_PORT 443;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;

        fastcgi_pass wordpress:9000;
    }
    # location ~ \.php$ {
    #     include fastcgi_params;
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    #     fastcgi_param HTTPS on;
    #     fastcgi_param HTTP_HOST $host;
    #     fastcgi_param SERVER_PORT 443;

    #     fastcgi_pass wordpress:9000;
    # }
}
# docker compose down -v
# docker system prune -af --volumes
# docker compose up --build

# server
# {
#     listen 443 ssl;

#     # server_name localhost 127.0.0.1 inception.42.fr;
#     ssl_certificate /etc/nginx/ssl/inception.crt;
#     ssl_certificate_key /etc/nginx/ssl/inception.key;
#     ssl_protocols TLSv1.2 TLSv1.3;

#     root /var/www/html;
#     index index.php;

#     location ~ \.php$
#     {
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         set $wordpress_upstream wordpress;
#         fastcgi_pass $wordpress_upstream:9000;
#         fastcgi_index index.php;
#     }
# }